export const repoSearch_indicina_page_1 = {
  search: {
    __typename: 'SearchResultItemConnection',
    repositoryCount: 21,
    edges: [
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE=',
        node: {
          __typename: 'Repository',
          id: 'R_kgDOGGFo9Q',
          url: 'https://github.com/aimejayd/Indicina',
          nameWithOwner: 'aimejayd/Indicina',
          updatedAt: '2021-09-22T02:18:34Z',
          description: 'Assessment Indicina',
          stargazerCount: 0,
          licenseInfo: null,
          primaryLanguage: null,
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjI=',
        node: {
          __typename: 'Repository',
          id: 'MDEwOlJlcG9zaXRvcnkzODg1OTc5NDc=',
          url: 'https://github.com/juanpsiar/indicinaJPSA',
          nameWithOwner: 'juanpsiar/indicinaJPSA',
          updatedAt: '2021-07-31T00:31:17Z',
          description: 'Technical Test JPSA ',
          stargazerCount: 0,
          licenseInfo: {
            __typename: 'License',
            name: 'MIT License',
          },
          primaryLanguage: {
            __typename: 'Language',
            name: 'CSS',
          },
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjM=',
        node: {
          __typename: 'Repository',
          id: 'R_kgDOGKXlqA',
          url: 'https://github.com/aimejayd/IndicinaEngineering',
          nameWithOwner: 'aimejayd/IndicinaEngineering',
          updatedAt: '2021-10-08T06:13:10Z',
          description: null,
          stargazerCount: 0,
          licenseInfo: null,
          primaryLanguage: {
            __typename: 'Language',
            name: 'JavaScript',
          },
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjQ=',
        node: {
          __typename: 'Repository',
          id: 'MDEwOlJlcG9zaXRvcnkzOTY5MDY2ODQ=',
          url: 'https://github.com/alvaroassmus/indicinaUrl',
          nameWithOwner: 'alvaroassmus/indicinaUrl',
          updatedAt: '2021-08-19T16:25:02Z',
          description:
            'URL shortening service using your programming language of choice',
          stargazerCount: 0,
          licenseInfo: {
            __typename: 'License',
            name: 'Other',
          },
          primaryLanguage: {
            __typename: 'Language',
            name: 'TypeScript',
          },
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjU=',
        node: {
          __typename: 'Repository',
          id: 'MDEwOlJlcG9zaXRvcnkxMjkzOTYwMjQ=',
          url: 'https://github.com/assistantmadman/indicina',
          nameWithOwner: 'assistantmadman/indicina',
          updatedAt: '2018-04-13T11:59:31Z',
          description: 'A handy video tagging app',
          stargazerCount: 0,
          licenseInfo: null,
          primaryLanguage: {
            __typename: 'Language',
            name: 'Python',
          },
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjY=',
        node: {
          __typename: 'Repository',
          id: 'MDEwOlJlcG9zaXRvcnkzODY5MzUzNTA=',
          url: 'https://github.com/deep-ux-ai/indicina',
          nameWithOwner: 'deep-ux-ai/indicina',
          updatedAt: '2021-07-17T13:01:08Z',
          description: null,
          stargazerCount: 0,
          licenseInfo: null,
          primaryLanguage: null,
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjc=',
        node: {
          __typename: 'Repository',
          id: 'R_kgDOGJ6gxA',
          url: 'https://github.com/shegzynova/indicina',
          nameWithOwner: 'shegzynova/indicina',
          updatedAt: '2021-10-03T11:51:18Z',
          description: null,
          stargazerCount: 0,
          licenseInfo: null,
          primaryLanguage: {
            __typename: 'Language',
            name: 'PHP',
          },
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjg=',
        node: {
          __typename: 'Repository',
          id: 'MDEwOlJlcG9zaXRvcnkyOTYyNzQ3Nzc=',
          url: 'https://github.com/jideabdqudus/indicina',
          nameWithOwner: 'jideabdqudus/indicina',
          updatedAt: '2020-11-06T18:58:09Z',
          description: 'Website for Indicina.co',
          stargazerCount: 0,
          licenseInfo: null,
          primaryLanguage: {
            __typename: 'Language',
            name: 'JavaScript',
          },
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjk=',
        node: {
          __typename: 'Repository',
          id: 'MDEwOlJlcG9zaXRvcnkyMTE3MzMwMTE=',
          url: 'https://github.com/Dubby20/indicina',
          nameWithOwner: 'Dubby20/indicina',
          updatedAt: '2019-09-30T00:25:38Z',
          description: null,
          stargazerCount: 0,
          licenseInfo: null,
          primaryLanguage: {
            __typename: 'Language',
            name: 'JavaScript',
          },
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjEw',
        node: {
          __typename: 'Repository',
          id: 'MDEwOlJlcG9zaXRvcnkzODUzNDEzODQ=',
          url: 'https://github.com/horlarme/indicina',
          nameWithOwner: 'horlarme/indicina',
          updatedAt: '2021-07-12T18:13:13Z',
          description: null,
          stargazerCount: 0,
          licenseInfo: null,
          primaryLanguage: {
            __typename: 'Language',
            name: 'PHP',
          },
        },
      },
    ],
    pageInfo: {
      __typename: 'PageInfo',
      startCursor: 'Y3Vyc29yOjE=',
      endCursor: 'Y3Vyc29yOjEw',
      hasNextPage: true,
      hasPreviousPage: false,
    },
  },
};
