export const userSearchResults__page_1 = {
  search: {
    __typename: 'SearchResultItemConnection',
    userCount: 57880,
    edges: [
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE=',
        node: {
          __typename: 'Organization',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjI=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjQ5MTg1',
          url: 'https://github.com/reactormonk',
          bio: '',
          name: 'Simon Hafner',
          email: '',
          login: 'reactormonk',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjM=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjYwODY5ODEw',
          url: 'https://github.com/reactdersleri',
          bio: 'React Dersleri anlatan Türkçe YouTube Kanalı',
          name: 'React Dersleri',
          email: '',
          login: 'reactdersleri',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjQ=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjM4NzE2NTU3',
          url: 'https://github.com/ReactExpert',
          bio: 'My philosophy is "where there is a will, there is a way". The good relationship is much more important than the budget.',
          name: 'Web Developer',
          email: '',
          login: 'ReactExpert',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjU=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjQzMDA2Mw==',
          url: 'https://github.com/reactivepixel',
          bio: "Ascii Art and BBS Door Games were my jam circa '89.",
          name: 'Chapman',
          email: '',
          login: 'reactivepixel',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjY=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjEzNjM3NA==',
          url: 'https://github.com/kmcclosk',
          bio: 'Node/React expert. ',
          name: 'React',
          email: '',
          login: 'kmcclosk',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjc=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjE5Mzc1NjQ3',
          url: 'https://github.com/ReactiioN1337',
          bio: 'Professional full stack developer and freetime (modern) C++ enthusiast with ❤️',
          name: null,
          email: '',
          login: 'ReactiioN1337',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjg=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjQ4MTE4MzI3',
          url: 'https://github.com/reacto11mecha',
          bio: '',
          name: 'Ezra Khairan Permana',
          email: '',
          login: 'reacto11mecha',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjk=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjQ4NTU1MTIx',
          url: 'https://github.com/greatSumini',
          bio: 'just developer',
          name: 'Choi Sumin',
          email: 'react@kakao.com',
          login: 'greatSumini',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjEw',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjEzNzY0MDM=',
          url: 'https://github.com/ReactiveRaven',
          bio: null,
          name: 'David Godfrey',
          email: 'reactiveraven@reactiveraven.co.uk',
          login: 'ReactiveRaven',
        },
      },
    ],
    pageInfo: {
      __typename: 'PageInfo',
      startCursor: 'Y3Vyc29yOjE=',
      endCursor: 'Y3Vyc29yOjEw',
      hasNextPage: true,
      hasPreviousPage: false,
    },
  },
};
