export const userSearchResults__page_2 = {
  search: {
    __typename: 'SearchResultItemConnection',
    userCount: 40,
    edges: [
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjEx',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjc0MTgyNjUz',
          url: 'https://github.com/Chidimma32',
          bio: null,
          name: null,
          email: '',
          login: 'Chidimma32',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjEy',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjgxMTQ3NjIz',
          url: 'https://github.com/chidimma-kate',
          bio: null,
          name: null,
          email: '',
          login: 'chidimma-kate',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjEz',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjUwMjY2MTQy',
          url: 'https://github.com/chidimma-okafor',
          bio: null,
          name: null,
          email: '',
          login: 'chidimma-okafor',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE0',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjY1NDU5OTEz',
          url: 'https://github.com/chidimma150',
          bio: null,
          name: null,
          email: '',
          login: 'chidimma150',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE1',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjc5NTg0MzE0',
          url: 'https://github.com/chidimmaijeoma',
          bio: null,
          name: null,
          email: '',
          login: 'chidimmaijeoma',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE2',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjU4OTE0NDQ3',
          url: 'https://github.com/chidimmaq35',
          bio: null,
          name: null,
          email: '',
          login: 'chidimmaq35',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE3',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjQ5MzQ2MzQw',
          url: 'https://github.com/chidimma25',
          bio: null,
          name: null,
          email: '',
          login: 'chidimma25',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE4',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjM2OTY4NTUw',
          url: 'https://github.com/Chidimma1',
          bio: null,
          name: null,
          email: '',
          login: 'Chidimma1',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE5',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjQ3NTg0MTMx',
          url: 'https://github.com/ChidimmaN',
          bio: null,
          name: null,
          email: '',
          login: 'ChidimmaN',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjIw',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjc5NzMzMjI3',
          url: 'https://github.com/Chidimma31',
          bio: null,
          name: null,
          email: '',
          login: 'Chidimma31',
        },
      },
    ],
    pageInfo: {
      __typename: 'PageInfo',
      startCursor: 'Y3Vyc29yOjEx',
      endCursor: 'Y3Vyc29yOjIw',
      hasNextPage: true,
      hasPreviousPage: true,
    },
  },
};
