export const userSearchResults__page_1 = {
  search: {
    __typename: 'SearchResultItemConnection',
    userCount: 753,
    edges: [
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjM3MDY5MzI4',
          url: 'https://github.com/chidi',
          bio: null,
          name: null,
          email: '',
          login: 'chidi',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjI=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjE3ODc5Njcy',
          url: 'https://github.com/chidiwilliams',
          bio: '',
          name: 'Chidi Williams',
          email: 'williamschidi1@gmail.com',
          login: 'chidiwilliams',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjM=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjU0MTgxMTM=',
          url: 'https://github.com/chidimo',
          bio: 'Frontend Developer\r\n\r\nAuthor at smashing magazine: https://www.smashingmagazine.com/author/chidi-orji/\r\n',
          name: 'Orji Chidi Matthew',
          email: 'orjichidi95@gmail.com',
          login: 'chidimo',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjQ=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjI1NDUwMDY2',
          url: 'https://github.com/kulloveth',
          bio: 'Mobile enthusiast. Android||Java|Kotlin',
          name: 'Chidi Loveth',
          email: 'c.lovethnwokike@gmail.com',
          login: 'kulloveth',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjU=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjExMDQ3MjQ3',
          url: 'https://github.com/Chidiemeh184',
          bio: 'Find me on Youtube \r\n-->  Chilly bean iOS (old channel)\r\n--> The iOS Journey (new channel)',
          name: 'Chidi Emeh',
          email: 'chidiemeh184@gmail.com',
          login: 'Chidiemeh184',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjY=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjI1MDk4NDI3',
          url: 'https://github.com/chidindu-ogbonna',
          bio: 'Applied AI Engineer\r\n\r\n',
          name: 'Promise Ogbonna ',
          email: 'promise.bones@gmail.com',
          login: 'chidindu-ogbonna',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjc=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjQ0NzM3NjQ0',
          url: 'https://github.com/chidibede',
          bio: '\r\n Fullstack developer, Machine Learning Enthusiast. Languages Used: [TypeScript, JavaScript and Python], tools include [Node, Django, React, Next, express]',
          name: 'Chidi Enwereji',
          email: 'chidibede@gmail.com',
          login: 'chidibede',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjg=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjIyNDM1MDk5',
          url: 'https://github.com/Okoyecb',
          bio: 'Program Manager ',
          name: 'Chidi Okoye',
          email: 'okoyecb@gmail.com',
          login: 'Okoyecb',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjk=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjc5MzE3NTA=',
          url: 'https://github.com/ekumachidi',
          bio: '',
          name: 'Ekuma Chidi',
          email: '',
          login: 'ekumachidi',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjEw',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjEzMzk1NjM0',
          url: 'https://github.com/ChidinmaKO',
          bio: 'Python • Javascript • Typescript • Machine & Deep Learning • Curious',
          name: 'Chidinma Kalu',
          email: 'kchidinmavictoria@gmail.com',
          login: 'ChidinmaKO',
        },
      },
    ],
    pageInfo: {
      __typename: 'PageInfo',
      startCursor: 'Y3Vyc29yOjE=',
      endCursor: 'Y3Vyc29yOjEw',
      hasNextPage: true,
      hasPreviousPage: false,
    },
  },
};
