export const userSearchResults__page_1 = {
  search: {
    __typename: 'SearchResultItemConnection',
    userCount: 40,
    edges: [
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjg4NDM2OTky',
          url: 'https://github.com/Chidimm',
          bio: null,
          name: null,
          email: '',
          login: 'Chidimm',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjI=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjIwODY4MDAw',
          url: 'https://github.com/chidimmaibeh',
          bio: 'I completed a master of science in software development at Maryville University. Interest:  application development, cybersecurity, and information assurance.',
          name: 'Chidimma',
          email: '',
          login: 'chidimmaibeh',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjM=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjc4OTgzNjAw',
          url: 'https://github.com/chidimmaNworah',
          bio: 'Software Engineer',
          name: 'Chidimma Nworah',
          email: '',
          login: 'chidimmaNworah',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjQ=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjU0MjkxODE4',
          url: 'https://github.com/chidimmaesione',
          bio: null,
          name: null,
          email: '',
          login: 'chidimmaesione',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjU=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjg2MjA1MTU1',
          url: 'https://github.com/chidimmaabasilim',
          bio: null,
          name: null,
          email: '',
          login: 'chidimmaabasilim',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjY=',
        node: {
          __typename: 'User',
          id: 'U_kgDOBXsTfA',
          url: 'https://github.com/Chidimma-Onyinye',
          bio: null,
          name: null,
          email: '',
          login: 'Chidimma-Onyinye',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjc=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjg1NDU4NTMy',
          url: 'https://github.com/Chidimma01',
          bio: '18CN024503',
          name: null,
          email: '',
          login: 'Chidimma01',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjg=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjc5NzMzNTA4',
          url: 'https://github.com/Chidimma3',
          bio: null,
          name: null,
          email: '',
          login: 'Chidimma3',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjk=',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjg2MjkyOTYw',
          url: 'https://github.com/Chidimma92',
          bio: null,
          name: null,
          email: '',
          login: 'Chidimma92',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjEw',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjI5NzYzMDU4',
          url: 'https://github.com/chidimma-nzerem',
          bio: '',
          name: 'Chidimma Nzerem',
          email: '',
          login: 'chidimma-nzerem',
        },
      },
    ],
    pageInfo: {
      __typename: 'PageInfo',
      startCursor: 'Y3Vyc29yOjE=',
      endCursor: 'Y3Vyc29yOjEw',
      hasNextPage: true,
      hasPreviousPage: false,
    },
  },
};
