export const userSearchResults__page_2 = {
  search: {
    __typename: 'SearchResultItemConnection',
    userCount: 753,
    edges: [
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjEx',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjc1OTgwMTY0',
          url: 'https://github.com/Chidi-nwachukwu',
          bio: 'passionate about #learning  #software engineer#web_dev #team_work.\r\n',
          name: 'British',
          email: 'nwachukwuchidi081@gmail.com',
          login: 'Chidi-nwachukwu',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjEy',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjU3NTcxMjIy',
          url: 'https://github.com/ChidiNweze',
          bio: 'Eng student @uWaterloo.',
          name: 'Chidi Nweze',
          email: '',
          login: 'ChidiNweze',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjEz',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjMzNjkyNDc1',
          url: 'https://github.com/chidi-ekeoma',
          bio: '',
          name: 'Chidi E',
          email: '',
          login: 'chidi-ekeoma',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE0',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjM4NTY1MzQ5',
          url: 'https://github.com/chidioguejiofor',
          bio: 'I am interested in NodeJS and Python technologies and currently working at Andela',
          name: 'Chidiebere Ogujeiofor',
          email: '',
          login: 'chidioguejiofor',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE1',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjY0OTA1MjQ0',
          url: 'https://github.com/chidinmanze',
          bio: 'Web developer with a certificate in full-stack web development from Michigan State University.\r\n\r\n',
          name: 'Chidinma Nze',
          email: 'chidinma.ogbuaku@gmail.com',
          login: 'chidinmanze',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE2',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjI4ODI0NDc3',
          url: 'https://github.com/ChidiChuks',
          bio: 'Curious and adventurous. ',
          name: 'Chidiebere Chukwuma',
          email: 'chukschiboy@gmail.com',
          login: 'ChidiChuks',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE3',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjMwNDM0MTQ2',
          url: 'https://github.com/ChidinmaOrajiaku',
          bio: '',
          name: null,
          email: '',
          login: 'ChidinmaOrajiaku',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE4',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjI5NzgzNzU3',
          url: 'https://github.com/chidiewenike',
          bio: 'Software Engineer @ Microsoft || \r\n\r\nAI, Automation, Robotics Enthusiast || Hackathon Frequenter',
          name: 'Chidi Ewenike',
          email: '',
          login: 'chidiewenike',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjE5',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjMzMDAwMTQ2',
          url: 'https://github.com/ikeohachidi',
          bio: 'Coding and chilling',
          name: 'Ikeoha Chidi',
          email: 'ikeohachidi@gmail.com',
          login: 'ikeohachidi',
        },
      },
      {
        __typename: 'SearchResultItemEdge',
        cursor: 'Y3Vyc29yOjIw',
        node: {
          __typename: 'User',
          id: 'MDQ6VXNlcjM1NTk2NDk1',
          url: 'https://github.com/chidiebereojingwa',
          bio: 'Qualified Full Stack Developer\r\nfamiliar with a wide range of\r\nprogramming utilities and\r\nlanguages. Knowledgeable of\r\nbackend and frontend development',
          name: 'Chidiebere Ojingwa',
          email: '',
          login: 'chidiebereojingwa',
        },
      },
    ],
    pageInfo: {
      __typename: 'PageInfo',
      startCursor: 'Y3Vyc29yOjEx',
      endCursor: 'Y3Vyc29yOjIw',
      hasNextPage: true,
      hasPreviousPage: true,
    },
  },
};
